language: minimal
dist: bionic
sudo: false

cache:
  directories:
    - $HOME/.cache/build

before_install:
  - ./extra/prepare.sh

script:
  - ./extra/buildall.sh
  - ./extra/publish.sh

env:
  global:
    - sfall_version=4.1.9.1
    - mpack_version=4.1.9.1
    - mod_name=party_orders
    - mods_dir=mods
    - extra_dir=extra
    - bin_dir=extra/bin

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: party_orders*.zip
  skip_cleanup: true
  on:
    tags: true
    branch: master
