name: Poify/Unpoify
on:
  push:
    branches:
      - master
    paths:
      - "data/text/**"

jobs:
  msg2po:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Poify/Unpoify
        uses: BGforgeNet/msg2po@dev
        with:
          poify: true
          unpoify: true
          dir2msgstr: true
          single_commit: true
